#!/bin/sh
# [https://faq.i3wm.org/question/239/how-do-i-suspendlockscreen-and-logout.1.html]

lock() {
    # [2019-01-31 acizov@gmail.com] only works iff gdm3 is disabled
    xset dpms 0 0 5
    (i3lock -n -f -c 000000 && xset dpms 0 0 0) &
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
